Checks for java and exits if no JDK installed
Checks for java first in JAVA_HOME then in PATH. If doesn't encounter it
errors out with a link to install openjdk

diff --git a/cli/archive/partiql b/cli/archive/partiql
--- a/cli/archive/partiql
+++ b/cli/archive/partiql
@@ -2,9 +2,15 @@
 
 BASEDIR=`dirname "$0" 2>/dev/null`
 
-JAVA=java
 if test -n "$JAVA_HOME"; then
     JAVA="$JAVA_HOME/bin/java"
+elif command -v java > /dev/null; then
+    JAVA=java
+else
+    echo "Java not found! Please install the Java JDK https://openjdk.java.net/"
+    echo "Press any key to exit"
+    read
+    exit 1
 fi
 
 $JAVA -jar $BASEDIR/partiql-cli.jar
